ALTER TABLE api_docpage ENGINE=InnoDB;
ALTER TABLE auth_group ENGINE=InnoDB;
ALTER TABLE auth_group_permissions ENGINE=InnoDB;
ALTER TABLE auth_message ENGINE=InnoDB;
ALTER TABLE auth_permission ENGINE=InnoDB;
ALTER TABLE auth_user ENGINE=InnoDB;
ALTER TABLE auth_user_groups ENGINE=InnoDB;
ALTER TABLE auth_user_user_permissions ENGINE=InnoDB;
ALTER TABLE base_celeryresponse ENGINE=InnoDB;
ALTER TABLE django_admin_log ENGINE=InnoDB;
ALTER TABLE django_content_type ENGINE=InnoDB;
ALTER TABLE django_session ENGINE=InnoDB;
ALTER TABLE django_site ENGINE=InnoDB;
ALTER TABLE jetpack_attachment ENGINE=InnoDB;
ALTER TABLE jetpack_attachment_revisions ENGINE=InnoDB;
ALTER TABLE jetpack_emptydir ENGINE=InnoDB;
ALTER TABLE jetpack_emptydir_revisions ENGINE=InnoDB;
ALTER TABLE jetpack_module ENGINE=InnoDB;
ALTER TABLE jetpack_module_revisions ENGINE=InnoDB;
ALTER TABLE jetpack_package ENGINE=InnoDB;
ALTER TABLE jetpack_packagerevision ENGINE=InnoDB;
ALTER TABLE jetpack_packagerevision_dependencies ENGINE=InnoDB;
ALTER TABLE jetpack_sdk ENGINE=InnoDB;
ALTER TABLE person_limit ENGINE=InnoDB;
ALTER TABLE person_profile ENGINE=InnoDB;

ALTER TABLE jetpack_attachment ADD FOREIGN KEY (author_id) REFERENCES auth_user(id);
ALTER TABLE jetpack_attachment_revisions ADD FOREIGN KEY (attachment_id) REFERENCES jetpack_attachment(id);
ALTER TABLE jetpack_attachment_revisions ADD FOREIGN KEY (packagerevision_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_packagerevision ADD FOREIGN KEY (package_id) REFERENCES jetpack_package(id);
ALTER TABLE jetpack_packagerevision ADD FOREIGN KEY (author_id) REFERENCES auth_user (id);
ALTER TABLE jetpack_packagerevision ADD FOREIGN KEY (origin_id) REFERENCES jetpack_packagerevision (id);
ALTER TABLE jetpack_packagerevision ADD FOREIGN KEY (sdk_id) REFERENCES jetpack_sdk(id);
ALTER TABLE jetpack_packagerevision_dependencies ADD FOREIGN KEY (from_packagerevision_id) REFERENCES jetpack_packagerevision (id);
ALTER TABLE jetpack_packagerevision_dependencies ADD FOREIGN KEY (to_packagerevision_id) REFERENCES jetpack_packagerevision (id);
ALTER TABLE jetpack_package ADD FOREIGN KEY (author_id) REFERENCES auth_user(id);
ALTER TABLE jetpack_package ADD FOREIGN KEY (latest_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_package ADD FOREIGN KEY (version_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_module_revisions ADD FOREIGN KEY (module_id) REFERENCES jetpack_module(id);
ALTER TABLE jetpack_module_revisions ADD FOREIGN KEY (packagerevision_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_module ADD FOREIGN KEY (author_id) REFERENCES auth_user(id);
ALTER TABLE jetpack_emptydir ADD FOREIGN KEY (author_id) REFERENCES auth_user(id);
ALTER TABLE jetpack_emptydir_revisions ADD FOREIGN KEY (emptydir_id) REFERENCES jetpack_emptydir(id);
ALTER TABLE jetpack_emptydir_revisions ADD FOREIGN KEY (packagerevision_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_sdk ADD FOREIGN KEY (core_lib_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE jetpack_sdk ADD FOREIGN KEY (kit_lib_id) REFERENCES jetpack_packagerevision(id);
ALTER TABLE person_profile ADD FOREIGN KEY (user_id) REFERENCES auth_user(id);
ALTER TABLE auth_permission ADD FOREIGN KEY (content_type_id) REFERENCES django_content_type (id);
ALTER TABLE auth_group_permissions ADD FOREIGN KEY (permission_id) REFERENCES auth_permission (id);
ALTER TABLE auth_group_permissions ADD FOREIGN KEY (group_id) REFERENCES auth_group (id);
ALTER TABLE auth_user_user_permissions ADD FOREIGN KEY (permission_id) REFERENCES auth_permission (id);
ALTER TABLE auth_user_groups ADD FOREIGN KEY (group_id) REFERENCES auth_group (id);
ALTER TABLE auth_user_user_permissions ADD FOREIGN KEY (user_id) REFERENCES auth_user (id);
ALTER TABLE auth_user_groups ADD FOREIGN KEY (user_id) REFERENCES auth_user (id);
ALTER TABLE auth_message ADD FOREIGN KEY (user_id) REFERENCES auth_user (id);